# 生产环境专用配置覆盖
version: '3.8'

services:
  backend:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  management:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  db:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 生产环境移除init.sql挂载

  nginx:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

# 生产环境卷配置（使用外部卷）
volumes:
  postgres_data:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
  frontend_node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_frontend_node_modules
  backend_node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_backend_node_modules
  management_node_modules:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_management_node_modules
